#!/usr/bin/env python3
# Embed a TTF file as a C byte array header, so the raylib backends can
# LoadFontFromMemory() a bundled font with no runtime asset file (mirrors how
# src/font_atlas.h embeds the iOS glyph atlas). Regenerate after changing the
# font: scripts/embed_ttf.py <in.ttf> <symbol> <out.h>
import os
import sys


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: embed_ttf.py <in.ttf> <symbol> <out.h>")
    src, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(src, "rb").read()
    if data[:4] not in (b"\x00\x01\x00\x00", b"true", b"OTTO", b"ttcf"):
        sys.exit("embed_ttf: %s does not look like a TTF/OTF" % src)
    guard = "%s_H" % sym.upper()
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("// Generated by scripts/embed_ttf.py from %s — do not edit by hand.\n"
                % os.path.basename(src))
        f.write("#ifndef %s\n#define %s\n" % (guard, guard))
        f.write("static const unsigned char %s[] = {\n" % sym)
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned int %s_len = %du;\n" % (sym, len(data)))
        f.write("#endif\n")
    print("embed_ttf: wrote %s (%d bytes -> %s)" % (out, len(data), sym))


if __name__ == "__main__":
    main()
