// Bakes the bundled Nunito UI font to a C header the iOS Metal renderer embeds,
// so iOS text matches the raylib backends (which LoadFontFromMemory the same
// TTF). Needs a GL context (LoadFontEx uploads a texture), so run with a display
// (WSLg / X) or headless under xvfb:
//
//   gcc scripts/gen_font_atlas.c -Ithird_party/raylib-install/include \
//       -Lthird_party/raylib-install/lib -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 \
//       -o build/gen_font_atlas
//   ./build/gen_font_atlas > src/font_atlas.h        (or xvfb-run -a ...)
//
// Output: the atlas alpha bitmap + per-glyph metrics (rec, offset, advance) +
// baseSize, enough to reproduce DrawTextEx/MeasureTextEx. The bottom-right 8x8
// pixels are forced opaque so the Metal backend can sample a "white block" for
// solid fills under LINEAR filtering (a single texel would bleed).
#include "raylib.h"
#include <stdio.h>

#define ATLAS_BASE 96   // bake size; layout is base-independent, this sets quality/atlas size

int main(void) {
    SetTraceLogLevel(LOG_ERROR);
    SetConfigFlags(FLAG_WINDOW_HIDDEN);
    InitWindow(64, 64, "gen_font_atlas");

    Font font = LoadFontEx("third_party/fonts/nunito/Nunito-SemiBold.ttf",
                           ATLAS_BASE, NULL, 0);  // NULL,0 = default 95 ASCII glyphs
    Image img = LoadImageFromTexture(font.texture);
    ImageFormat(&img, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
    unsigned char* px = (unsigned char*)img.data;
    int W = img.width, H = img.height;

    // Force an 8x8 opaque block at the bottom-right for the solid-fill texel.
    for (int yy = H - 8; yy < H; yy++)
        for (int xx = W - 8; xx < W; xx++)
            if (yy >= 0 && xx >= 0) px[(yy * W + xx) * 4 + 3] = 255;

    printf("// Generated by scripts/gen_font_atlas.c — bundled Nunito UI font.\n");
    printf("// Do not edit by hand; regenerate with the command in that file.\n");
    printf("#ifndef FONT_ATLAS_INCLUDED\n#define FONT_ATLAS_INCLUDED\n\n");
    printf("#define FONT_ATLAS_W %d\n", W);
    printf("#define FONT_ATLAS_H %d\n", H);
    printf("#define FONT_BASE_SIZE %d\n", font.baseSize);
    printf("#define FONT_GLYPH_COUNT %d\n\n", font.glyphCount);

    // Alpha coverage of the atlas (one byte per pixel).
    printf("static const unsigned char font_atlas_alpha[FONT_ATLAS_W * FONT_ATLAS_H] = {\n");
    for (int i = 0; i < W * H; i++) {
        printf("%u,", px[i * 4 + 3]);
        if ((i % 32) == 31) printf("\n");
    }
    printf("};\n\n");

    printf("typedef struct { int value; float rx, ry, rw, rh; int ox, oy, adv; } FontGlyph;\n");
    printf("static const FontGlyph font_glyphs[FONT_GLYPH_COUNT] = {\n");
    for (int i = 0; i < font.glyphCount; i++) {
        Rectangle r = font.recs[i];
        GlyphInfo g = font.glyphs[i];
        printf("{%d,%g,%g,%g,%g,%d,%d,%d},\n",
               g.value, r.x, r.y, r.width, r.height, g.offsetX, g.offsetY, g.advanceX);
    }
    printf("};\n\n#endif // FONT_ATLAS_INCLUDED\n");

    UnloadImage(img);
    CloseWindow();
    return 0;
}
